### ISSUE TITLE
[Question] Inclusion of (remote) yaml files

### ISSUE THREAD

**Issue by fruitl00p** [deeepamin/gitlab-ci-aid#110]
Hi!

Thanks for the plugin which helps writing Gitlab CI/CD yaml files! I do have a question that i haven't been able to find anywhere: will you add the ability to include remote CI/CD files as well?

```yaml
include:
  - project: 'some/other/repository/with/templates'
    file: '/some/nested/.gitlab-ci.yml'
```

That would make it alot easier to include externally split gitlab config / template files as described here: https://docs.gitlab.com/ci/yaml/includes/ (and here https://medium.com/@david_haylock/organising-your-gitlab-ci-cd-pipeline-from-monolithic-to-modular-2847e0b43320)

Thanks!
