### ISSUE TITLE
Ability to navigate to overrides, or super

### ISSUE THREAD

**Issue by bric3** [deeepamin/gitlab-ci-aid#111]
Suppose pipeline like that

Navigating up/down pipelines, or to parent / overridden before/after_script could be useful

```yaml
.gradle:
  script:
    - ...
  after_script:
    - echo gradle stats...

.build:
  extends: .gradle
  ...

build_a:
  extends: .build
  script:
   - ...
  after_script:
    - echo override
```
