### ISSUE TITLE
Job is not highlighted or auto completed when stage element is added via alias and override 

### ISSUE THREAD

**Issue by deeepamin** [deeepamin/gitlab-ci-aid#21]
When an alias and override (<<: *) is used to refer values from another job which contains stage element, the job is not parsed or suggested in auto completion. 

### Example
```yaml
test-job: &test
  stage: test-stage

test-job2:
  <<: *test
```
In this example: test-job2 is not highlighted or suggested in auto completion.
