### ISSUE TITLE
Wrong path delimiters on Windows

### ISSUE THREAD

**Issue by shokurov** [deeepamin/gitlab-ci-aid#29]
On Windows machine this fragment gives me a warning "file not found":

```yaml
  trigger:
    include:
      - local: postgresql/latest/stress-tests/.gitlab-stress-tests.yml
    strategy: depend
```

When I change path delimiters to `\` the error disappears. Obviously that would prevent execution on Linux, so I have to cope with the warning instead.
