### ISSUE TITLE
Support for CI/CD inputs

### ISSUE THREAD

**Issue by denniseffing** [deeepamin/gitlab-ci-aid#42]
GitLab CI offers [CI/CD Inputs](https://docs.gitlab.com/ci/inputs) to define input parameters that can be passed to the configuration file, allowing consumers to customize reusable CI configurations. They provide typed parameters for reusable templates with built-in validation at pipeline creation time and are more flexible than CI/CD variables.

It would be nice if the plugin supported their syntax:

```yaml
spec:
  inputs:
    job-prefix:     # Mandatory string input
      description: "Define a prefix for the job name"
    job-stage:      # Optional string input with a default value when not provided
      default: test
    environment:    # Mandatory input that must match one of the options
      options: ['test', 'staging', 'production']
    concurrency:
      type: number  # Optional numeric input with a default value when not provided
      default: 1
    version:        # Mandatory string input that must match the regular expression
      type: string
      regex: ^v\d\.\d+(\.\d+)$
    export_results: # Optional boolean input with a default value when not provided
      type: boolean
      default: true
```
