### ISSUE TITLE
Inputs incorrectly validated with 1.5.0

### ISSUE THREAD

**Issue by glensc** [deeepamin/gitlab-ci-aid#71]
I see there's inputs validation since 1.2.0:
- https://github.com/deeepamin/gitlab-ci-aid/issues/42

However it seems to get confused and think I'm editing main yaml file not component.

<img width="565" alt="Image" src="https://github.com/user-attachments/assets/597b0da6-bac3-4286-a6bc-1de6f5b921eb" />

<img width="833" alt="Image" src="https://github.com/user-attachments/assets/44dd29cc-2fa4-4528-888d-e745988c545b" />

<img width="723" alt="Image" src="https://github.com/user-attachments/assets/ee5a2c77-6bfe-4ef7-ad61-aea34d18f705" />

----

<details><summary>Example YAML</summary>

```yml
spec:
  inputs:
    name:
      type: string
      default: build
      description: Name of the job (must be a valid CI job name)
    stage:
      type: string
      default: build
      description: Pipeline stage to run this job in (e.g., "build")
    context:
      type: string
      default: .
      description: Docker build context path (relative to repo root)
    tag:
      type: string
      required: true
      description: Fully qualified Docker image tag (e.g., "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME")

---

$[[ inputs.name ]]:
  stage: $[[ inputs.stage ]]
  dependencies: []
  needs: []
  variables:
    DOCKER_TAG: $[[ inputs.tag ]]
    DOCKER_CONTEXT: $[[ inputs.context ]]
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t "$DOCKER_TAG" "$DOCKER_CONTEXT"
    - docker push "$DOCKER_TAG"

# vim:ts=2:sw=2:et
```

</details>
