### ISSUE TITLE
Custom stages not recognised

### ISSUE THREAD

**Issue by macdjord** [deeepamin/gitlab-ci-aid#86]
```yaml
# The stages of our pipeline, in order:
stages:
  - "build"
  - "unittest"

########
# Jobs #
########

# Build the Docker images and save them in the registry
build:
  stage: "build"

# Run unit tests on the newly built images
unittest:
  stage: "unittest"
```
`stage: "unittest"` is highlighted as an error, with the message "Undefined stage '"unittest"' or not present in pipeline stages".

Tested in 1.8.0
